### ISSUE TITLE
Can't Name created servers, can't delete servers, can't upload saves

### ISSUE THREAD

**Issue by silentdis** [mrhid6/SatisfactoryServerManager#136]
Fresh Ubuntu 20.04 in a CT on Proxmox. Packages are up-to-date, i386 architecture is added (for SteamCMD), multiverse enabled, SteamCMD installed. 32GiB disk, 16GiB memory, 16 3ghz cores. Fuse and Nesting both enabled in Proxmox.

SSM install performed as root, worked fine, no errors.

I was able to log in and set my password without issue.

I went to servers, and chose "Create Server". After a few moments, I get an error in the bottom-right corner informing me "Failed to create server" with no further information, but a item called SSMAgent1 appears in the list.

I am unable to start SSMAgent1; it just sits there after clicking.
I am unable to edit any of the settings for SSMAgent1.
I am unable to delete SSMAgent1, clicking the link just sits there.
I am unable to upload a save; gives error "Save couldn't be uploaded!" but it does show up in /home/ssm/.SatisfactoryServerManager/temp.

Rebooting the server, SSM comes back up as it should, but all problems noted still occur.

Log file attached from /home/ssm/.SatisfactoryServerManager/logs/ - but there's not much in here.
[20211128-SSM.log](https://github.com/mrhid6/SatisfactoryServerManager/files/7614206/20211128-SSM.log)

**Comment by silentdis** [comment]
On the off-chance something got missed, I performed an upgrade, just to be sure:

```
# wget -q https://git.io/Je7rx -O - | bash /dev/stdin "--update"
#-----------------------------#
#      _____ _____ __  __     #
#     / ____/ ____|  \/  |    #
#    | (___| (___ | \  / |    #
#     \___ \\___ \| |\/| |    #
#     ____) |___) | |  | |    #
#    |_____/_____/|_|  |_|    #
#-----------------------------#
# Satisfactory Server Manager #
#-----------------------------#
Installing Prereqs
Installing Docker
Updating SSM v1.1.9 to v1.1.9 ...
Stopping SSM Service
* Downloading SSM
* Cleanup
Creating SSM Service
* Removing Old SSM Service
* Create SSM Service
* Start SSM Service
```
Issue persists as described above

**Comment by mrhid6** [comment]
Run the application using /opt/SSM/SatisfactoryServerManager

**Comment by mrhid6** [comment]
See what errors show up

**Comment by silentdis** [comment]
> Run the application using /opt/SSM/SatisfactoryServerManager

As ssm:
```
~$ /opt/SSM/SatisfactoryServerManager
2021-11-28 19:38:06:698 [INFO]  Set debug mode to false
2021-11-28 19:38:05.323 INFO  [LOGGER] - Log Directory: /home/ssm/.SatisfactoryServerManager/logs
2021-11-28 19:38:07.395 INFO  [APP] [PREINIT] - Loading Configs..
2021-11-28 19:38:07.406 INFO  [APP] [PREINIT] - Starting SSM..
2021-11-28 19:38:07.408 INFO  [APP] [EXPRESS] - Starting Express..
2021-11-28 19:38:07.412 INFO  [APP] [EXPRESS] - Setup Express Static Routes..
2021-11-28 19:38:07.412 INFO  [APP] [EXPRESS] - Finished
2021-11-28 19:38:07.413 INFO  [APP] [EXPRESS] - Setup Express Routers..
2021-11-28 19:38:07.496 INFO  [APP] [EXPRESS] - Finished
2021-11-28 19:38:07.496 INFO  [APP] [EXPRESS] - Started Express.
Uncaught Exception...
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1319:16)
    at listenInCluster (node:net:1367:12)
    at Server.listen (node:net:1454:7)
    at AppServer.startExpress (/snapshot/SSM/app.js)
    at /snapshot/SSM/app.js
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1848:13)
    at node:internal/main/run_main_module:17:47
Cleanup Started ...
Could not close connections in time, forcefully shutting down
```
As root:
```
~# /opt/SSM/SatisfactoryServerManager
2021-11-28 19:39:18:321 [INFO]  Set debug mode to false
2021-11-28 19:39:16.948 INFO  [LOGGER] - Log Directory: /root/.SatisfactoryServerManager/logs
2021-11-28 19:39:19.015 INFO  [APP] [PREINIT] - Loading Configs..
2021-11-28 19:39:19.026 INFO  [APP] [PREINIT] - Starting SSM..
2021-11-28 19:39:19.029 INFO  [APP] [EXPRESS] - Starting Express..
2021-11-28 19:39:19.032 INFO  [APP] [EXPRESS] - Setup Express Static Routes..
2021-11-28 19:39:19.032 INFO  [APP] [EXPRESS] - Finished
2021-11-28 19:39:19.034 INFO  [APP] [EXPRESS] - Setup Express Routers..
2021-11-28 19:39:19.116 INFO  [APP] [EXPRESS] - Finished
2021-11-28 19:39:19.116 INFO  [APP] [EXPRESS] - Started Express.
Uncaught Exception...
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1319:16)
    at listenInCluster (node:net:1367:12)
    at Server.listen (node:net:1454:7)
    at AppServer.startExpress (/snapshot/SSM/app.js)
    at /snapshot/SSM/app.js
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at process.runNextTicks [as _tickCallback] (node:internal/process/task_queues:65:3)
    at Function.runMain (pkg/prelude/bootstrap.js:1848:13)
    at node:internal/main/run_main_module:17:47
Cleanup Started ...
Could not close connections in time, forcefully shutting down
```

**Comment by mrhid6** [comment]
Stop the derive before running it manually

**Comment by silentdis** [comment]
> Stop the service before running it manually

As ssm:
```
~$ systemctl stop SSM.service
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to stop 'SSM.service'.
Authenticating as: root
Password: 
==== AUTHENTICATION COMPLETE ===

~$ /opt/SSM/SatisfactoryServerManager
2021-11-28 19:53:52:752 [INFO]  Set debug mode to false
2021-11-28 19:53:51.382 INFO  [LOGGER] - Log Directory: /home/ssm/.SatisfactoryServerManager/logs
2021-11-28 19:53:53.458 INFO  [APP] [PREINIT] - Loading Configs..
2021-11-28 19:53:53.469 INFO  [APP] [PREINIT] - Starting SSM..
2021-11-28 19:53:53.471 INFO  [APP] [EXPRESS] - Starting Express..
2021-11-28 19:53:53.475 INFO  [APP] [EXPRESS] - Setup Express Static Routes..
2021-11-28 19:53:53.475 INFO  [APP] [EXPRESS] - Finished
2021-11-28 19:53:53.476 INFO  [APP] [EXPRESS] - Setup Express Routers..
2021-11-28 19:53:53.560 INFO  [APP] [EXPRESS] - Finished
2021-11-28 19:53:53.560 INFO  [APP] [EXPRESS] - Started Express.
2021-11-28 19:53:53.569 INFO  [APP] [INIT] - Server listening on port: (3000)..
2021-11-28 19:53:53.569 INFO  [SERVER_APP] [INIT] - Starting Server App...
```

At this point, the web service is back up. I attempted to start 2 of the servers I had 'created':
```
{ id: '4' }
2021-11-28 19:55:20.399 INFO  [AGENT_HANDLER] - Starting Agent...
{ id: '1' }
2021-11-28 19:55:40.394 INFO  [AGENT_HANDLER] - Starting Agent...
```
They hung forever.

I attempted to create a server:
```
2021-11-28 19:55:40.394 INFO  [AGENT_HANDLER] - Starting Agent...
{
  '3000/tcp': [ { HostPort: '3005' } ],
  '15781/udp': [ { HostPort: '15781' } ],
  '15004/udp': [ { HostPort: '15004' } ],
  '7781/udp': [ { HostPort: '7781' } ]
}
2021-11-28 19:58:07.607 INFO  [AGENT_HANDLER] - Created agent successfully!
```
Error on browser was "Failed to create server", but SSMAgent5 appears in the list now.

I attempted to delete any of the servers, no messages appeared in the console.

**Comment by mrhid6** [comment]
It does take a long time to start as it tries to download SSM in the docker on start. It could be that the request is timing out and causing the error. Might be worth looking at the network tab in chrome to see what error the request returns

**Comment by silentdis** [comment]
> It does take a long time to start as it tries to download SSM in the docker on start. It could be that the request is timing out and causing the error. Might be worth looking at the network tab in chrome to see what error the request returns

With Proxmox, I can see all CPU, memory, and network activity going on. I assure you, it's not doing anything.
![image](https://user-images.githubusercontent.com/11858026/143784411-ee640955-d771-49ee-b80e-ab91cbeb4480.png)

**Comment by mrhid6** [comment]
No in chrome you can see the requests to SSM and will return the error

**Comment by silentdis** [comment]
> No in chrome you can see the requests to SSM and will return the error

?

I'm uncertain what you mean.

Looking at the Chrome Dev Tools and sitting on the network tab just shows basic web data going back and forth between the webserver running and my system. I mean, I can see the POST and GET requests... but it doesn't reveal any further information.
![image](https://user-images.githubusercontent.com/11858026/143784945-73103f83-59ef-4fb8-a98e-59b204f36478.png)

When you say "Chrome", are you referring to my browser, or some aspect of the server called "chrome" that I don't know about?

**Comment by silentdis** [comment]
I did some thinking, and figured I'd see what happens with the docker container directly:
as ssm:
```
~$ docker start -ia SSMAgent1
ERRO[0000] error waiting for container: context canceled 
Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default365553552` failed with output: apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?

error: exit status 243
```

Please tell me this isn't just AppArmor sucking again...

```
~# systemctl stop apparmor
~# systemctl disable apparmor
Synchronizing state of apparmor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apparmor
Removed /etc/systemd/system/sysinit.target.wants/apparmor.service.
~# apt remove --purge apparmor
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  apparmor*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 1995 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 19496 files and directories currently installed.)
Removing apparmor (2.13.3-7ubuntu5.1) ...
Processing triggers for man-db (2.9.1-1) ...
(Reading database ... 19468 files and directories currently installed.)
Purging configuration files for apparmor (2.13.3-7ubuntu5.1) ...
Processing triggers for systemd (245.4-4ubuntu3.13) ...
~# reboot
```
Back in as ssm:
```
~$ docker start -ia SSMAgent1
Using Dev build of SSM
cat: /opt/SSM/version.txt: No such file or directory
Updating SSM  to v1.1.9 ...
* Downloading SSM
* Cleanup
SSM Service Skipped
2021-11-28 20:57:40:932 [INFO]  Set debug mode to false
2021-11-28 20:57:39.368 INFO  [LOGGER] - Log Directory: /home/ssm/.SatisfactoryServerManager/logs
2021-11-28 20:57:41.645 INFO  [APP] [PREINIT] - Loading Configs..
2021-11-28 20:57:41.664 INFO  [APP] [PREINIT] - Starting SSM..
2021-11-28 20:57:41.666 INFO  [APP] [EXPRESS] - Starting Express..
2021-11-28 20:57:41.672 INFO  [APP] [EXPRESS] - Setup Express Routers..
2021-11-28 20:57:41.748 INFO  [APP] [EXPRESS] - Finished
2021-11-28 20:57:41.748 INFO  [APP] [EXPRESS] - Started Express.
2021-11-28 20:57:41.756 INFO  [APP] [INIT] - Server listening on port: (3000)..
2021-11-28 20:57:41.756 INFO  [SERVER_APP] [INIT] - Starting Server App...
2021-11-28 20:57:41.758 INFO  [SFS_Handler] [INIT] - SFS Handler Initialized
2021-11-28 20:57:41.788 INFO  [SFS_Handler] - Checking SteamCmd binaries ..
2021-11-28 20:57:42.374 INFO  [SFS_Handler] - SteamCmd Downloaded!
2021-11-28 20:57:42.375 INFO  [SFS_Handler] - SteamCmd Initializing!
2021-11-28 20:58:00.022 DEBUG [SFS_Handler] - Getting Server State
2021-11-28 20:58:00.023 DEBUG [SFS_Handler] - Received Server State
2021-11-28 20:58:29.414 INFO  [SFS_Handler] - SteamCmd Initialised!
2021-11-28 20:58:29.414 INFO  [SFS_Handler] - Installed/Validated SteamCmd binaries
2021-11-28 20:58:29.414 DEBUG [SFS_Handler] - Getting Server State
2021-11-28 20:58:29.415 DEBUG [SFS_Handler] - Received Server State
2021-11-28 20:58:34.976 INFO  [Mod_Handler] [INIT] - Mod Handler Initialized
2021-11-28 20:58:34.976 INFO  [BACKUP_MANAGER] [INIT] - Backup Manager Initialized
2021-11-28 20:58:35.976 DEBUG [Mod_Handler] - Waiting for SteamCMD Install..
2021-11-28 20:58:35.976 DEBUG [Mod_Handler] - SteamCMD Install Completed!
2021-11-28 20:58:39.978 INFO  [BACKUP_MANAGER] - Starting Backup Task..
2021-11-28 20:58:40.009 INFO  [BACKUP_MANAGER] - Backup Task Finished!
2021-11-28 20:59:00.022 DEBUG [SFS_Handler] - Getting Server State
2021-11-28 20:59:00.023 DEBUG [SFS_Handler] - Received Server State
```
Goddamn you AppArmor.

I'm uncertain what needs doing to get your package back to functional with AppArmor going, but uninstalling this thing solves it.

**Comment by silentdis** [comment]
Had to delete the random created servers manually, because I still couldn't delete them from the website.
```
~# docker rm SSMAgent2
SSMAgent2
~# docker rm SSMAgent3
SSMAgent3
~# docker rm SSMAgent4
SSMAgent4
~# docker rm SSMAgent5
SSMAgent5
~# docker rm SSMAgent6
SSMAgent6
```
Now, I'm able to start SSMAgent1... but again, it just sits here after an initial pull, and does nothing further. I'm still unable to edit the server settings.
![image](https://user-images.githubusercontent.com/11858026/143786102-d56ea333-eceb-45ac-bd9d-413a43ae77b5.png)
![image](https://user-images.githubusercontent.com/11858026/143786115-ad3fc2e2-8551-4e2a-87d4-11e8e81e4ffa.png)

**Comment by silentdis** [comment]
I created another server, it starts, I still can't adjust anything, and it's not downloading.

**Comment by mrhid6** [comment]
Hmm so you see a version in the servers page?

**Comment by silentdis** [comment]
> Hmm so you see a version in the servers page?

Same screenshot as above.

**Comment by mrhid6** [comment]
go on to the docker `docker exec -it SSMAgent1 bash` and checkout the file `/home/ssm/.SatisfactoryServerManager/SSM.json`

**Comment by silentdis** [comment]
At this point, I'm giving up with SSM.

I'm sorry. Unlike most docker stuff I've seen, this is still extremely rough. It appears to be a great idea that simply does not function properly yet. I may check in on it in a few months, to see where things have gotten to, but for now, I'll just hand-manage things.

I apologize for taking your time, and I apologize I was unsuccessful with your tool.
